version: '3'

services:
  apache:
    image: 'php:8.3-apache'
    container_name: php-apache
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./aplicacao:/var/www/html
